In [1]:
import numpy as np
import pandas as pd

In [6]:
W = np.random.randn(1,10)

In [7]:
W

array([[ 1.88010276,  0.89390914,  0.51735246, -0.23711785,  0.32590532,
        -2.21816274, -0.9881835 , -1.01513037,  0.06759557, -1.37321453]])

https://mccormickml.com/2014/03/04/gradient-descent-derivation/
    

In [36]:
# Linear Regression

def linearRegression(X,Y,n_epochs,learning_rate):
    W = np.random.randn(X.shape[1],1)
    B = 0
    dW = np.zeros((X.shape[1],1))
    dB = 0
    for i in range(n_epochs):
        estimated = np.dot(X,W) + B
        SSE = np.sum(np.square(Y - estimated))
        MSE = SSE/X.shape[0]
        print(MSE)
        dW = 1/X.shape[0] * np.dot(X.T,(estimated-Y))
        dB = 1/X.shape[0] * np.sum((estimated-Y))
        W = W - learning_rate * dW
        B = B - learning_rate * dB
        print(W.shape)
    return W,B

In [37]:
#Logistic Regression
def logistic_regression(X,Y,n_epochs,learning_rate):
    W = np.random.randn(X.shape[1],1)
    B = 0
    for i in range(n_epochs):
        Z = np.dot(X,W) + B
        Y_hat = 1/(1+np.exp(-Z))
        print(Y_hat)
        cross_entropy = -1 * np.sum(Y * np.log(Y_hat) + (1-Y) * np.log(1-Y_hat))
        mean_cross_entropy = cross_entropy/X.shape[0]
        print(mean_cross_entropy)
        dW = 1/X.shape[0] * np.dot(X.T,(Y - Y_hat)) # Same as linear regression. Checked using partial derivatives.
        dB = 1/X.shape[0] * np.sum(Y-Y_hat)
        W = W - dW
        B = B - dB
    return W,B

In [38]:
X = np.random.randn(10,4)
Y = np.random.randint(low=2,size=(10,1))

In [36]:
def kMeansClustering(X,n_clusters,epochs):
    #Getting initial centroids
    centroids = X[np.random.choice(X.shape[0], n_clusters, replace=False)]
    for i in range(epochs):
        cluster = {}
        for j in range(X.shape[0]):
            dist = []
            for k in range(centroids.shape[0]):
                #Best way to calculate euclidean distance is using np.linalg.norm of the distance
                dist.append(np.linalg.norm(centroids[k] - X[j]))
            minDistance = dist.index(min(dist))
            # Check if the index has been updated to the cluster hashmap. If not, update it
            if minDistance not in cluster:
                cluster[minDistance] = [j]
            else:
                cluster[minDistance].append(j)
        for key,val in cluster.items():
            points = X[val]
            newPoint = np.sum(points,axis=0)
            centroids[key] = newPoint
        return cluster

In [1]:
def euclidean_distance(x,y):
    if len(x) != len(y):
        return -1
    else:
        length = len(x)
        ss = 0
        for i in range(length):
            ss+= (x[i] - y[i]) ** 2
        return ss ** (1/2)

In [54]:
class KNN:
    def __init__(self,k):
        self.k = k
    
    def vote(self,lis):
        count = {}
        for i in lis:
            if i not in count:
                count[i] = 1
            else:
                count[i]+=1
                
        maxVal = max(count.values())
        proba = maxVal/len(lis)
        for key,val in count.items():
            if val == maxVal:
                return key,proba
            
    def getMinIndex(self,distance):
        distCopy = [i for i in distance]
        distCopy.sort()
        ans = []
        ans = [distance.index(i) for i in distCopy[:self.k]]
        return ans
      
            
    def predict(self,train_X,train_Y,test_X):
        distDict = {}
        for i in range(len(test_X)):
            distance = []
            for j in range(len(train_X)):
                dist = euclidean_distance(train_X[j],test_X[i])
                distance.append(dist)
            distDict[i] = distance
        minDict = {}    
        for key,val in distDict.items():
            minDict[key] = self.getMinIndex(val)
        ans = [0] * len(test_X)
        proba = [0] * len(test_X)
        for key,val in minDict.items():
            relTest = [train_Y[i] for i in val]
            ans[key],proba[key] = self.vote(relTest)
        
        return ans,proba
            
        

In [55]:
k = KNN(k=2)

In [56]:
X_train = [[1,2,3],[4,5,6],[7,8,9],[0,2,4],[5,4,6]]
Y_train = [0,1,1,0,0]
X_test = [[3,2,4],[5,4,5]]



In [57]:
k.predict(train_X=X_train,train_Y=Y_train,test_X=X_test)

([0, 0], [1.0, 0.5])

In [40]:
from sklearn.neighbors import KNeighborsClassifier

In [58]:
X = np.array(X_train)
Y = np.array(Y_train)
xT = np.array(X_test)

In [49]:
knn = KNeighborsClassifier(n_neighbors=2)

In [59]:
knn.fit(X,Y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [60]:
knn.predict(xT)

array([0, 0])

In [61]:
knn.predict_proba(xT)

array([[ 1. ,  0. ],
       [ 0.5,  0.5]])

In [67]:
def summedAreaTable(mat):
    rows = len(mat)
    cols = len(mat[0])
    dp = [[0 for i in range(cols)] for j in range(rows)]
    for r in range(rows):
        for c in range(cols):
            if r==0 and c==0:
                dp[r][c] = mat[r][c]
            elif r == 0:
                dp[r][c] = mat[r][c] + dp[r][c-1]
            elif c == 0:
                dp[r][c] = mat[r][c] + dp[r-1][c]
            else:
                dp[r][c] = mat[r][c] + dp[r-1][c] + dp[r][c-1] - dp[r-1][c-1]            
    return dp

In [64]:
m = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

In [73]:
def rectangleSum(beginRow,endRow,beginCol,endCol,grid):
    summed = summedAreaTable(grid)
    if beginRow -1 >= 0:
        b = summed[beginRow-1][endCol]
    else:
        b = 0
    if beginCol-1 >= 0:
        c = summed[endRow][beginCol-1]
    else:
        c = 0
    if (beginRow-1 >=0 and beginCol-1>=0):
        d = summed[beginRow-1][beginCol-1]
    else:
        d = 0
        
    return summed[endRow][endCol] - b-c+d

In [74]:
rectangleSum(1,2,1,2,m)

34

In [77]:
rectangleSum(0,0,0,2,m)

6